### ISSUE TITLE
JDBC error?

### ISSUE THREAD

**Issue by ghost** [XIVStats/XIVStats-Gatherer-Java#2]
java -jar XIVStats-Gatherer-Java.jar 1 13500000

Connection failed! Please see output console
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/dbplayers
        at java.sql.DriverManager.getConnection(DriverManager.java:596)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at com.ffxivcensus.gatherer.GathererController.openConnection(GathererController.java:234)
        at com.ffxivcensus.gatherer.GathererController.main(GathererController.java:81)
java.lang.NullPointerException
        at com.ffxivcensus.gatherer.GathererController.main(GathererController.java:83)

I have JDBC connector installed.  Running Ubuntu on a VPS.

**Comment by ReidWeb** [comment]
@hmschreck are using the pre-compiled JAR from the releases tab? 

---

Or are you compiling and running the program yourself, if so you need to execute:

``` shell
mvn clean compile assembly:single
```

In the containing directory of the pom.xml file, this will pull in the required dependencies - including the MySQL adapter.

**Comment by ghost** [comment]
Using the precompiled one.

**Comment by ReidWeb** [comment]
Spinning up a fresh VM to test against now, will get back to you shortly.

**Comment by ReidWeb** [comment]
I believe the JARs are working now, I'm updating the releases as we speak. Please note the new command line parameters, documented in the readme (better doc for that coming shortly)

**Comment by ghost** [comment]
Thanks!

**Comment by ReidWeb** [comment]
[Fixed release](https://github.com/XIVStats/XIVStats-Gatherer-Java/releases/tag/v1.0pre2)

Apologies for any inconvenience I may have caused you, Jenkins was not distributing the dependencies as part of the JARs.
