### ISSUE TITLE
Add Samurai & Red Mage to gatherer

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats-Gatherer-Java#21]
Add Red Mage and Samurai to parse list.

Verify that all other jobs are being correctly evaluated - I cannot remember off the top of my head if they are index based or HTML text based on how it determines which is which.

**Comment by ReidWeb** [comment]
Upon further inspection the current level scraping will break now StormBlood has launched, as the levels are read from an array that has values in the order of their position on the web page, which has changed significantly with launch of 4.0/StormBlood.

**Comment by Crakila** [comment]
#23 resolves this issue :)
