### ISSUE TITLE
Option to output log of characters during scan

### ISSUE THREAD

**Issue by Pricetx** [XIVStats/XIVStats-Gatherer-Java#25]
Currently, the application outputs the results of what it's doing for each character to STDOUT. It would be nice if in addition to this I could have it output to a file so that I could then make some sort of progress bar in a webpage.

I can probably split STDOUT into multiple locations in the shell, but having a log file option just seems like it would be generally useful.

**Comment by matthewhillier** [comment]
I was playing around with adding log4j to replace the STDOUT prints, so this may be something achievable by separating out the character logs to a separate logging file. I'll see what I can whip up in the refactoring branch.

**Comment by ReidWeb** [comment]
> I was playing around with adding log4j to replace the STDOUT prints, so this may be something achievable by separating out the character logs to a separate logging file. I'll see what I can whip up in the refactoring branch.

@matthewhillier go for it 👍

**Comment by ReidWeb** [comment]
>  It would be nice if in addition to this I could have it output to a file so that I could then make some sort of progress bar in a webpage.

Perhaps worth looking at [this library](https://github.com/ctongfei/progressbar).

Coupled with @matthewhillier's idea of writing the log to a file, you could simply pipe the 'error' output to the active shell (and to a file), and then have a progress bar at the bottom. Seen this implemented in a few places before.

**Comment by ReidWeb** [comment]
> I can probably split STDOUT into multiple locations in the shell

Ref this: Probably unwise, `System.out` methods, while they are thread-safe are blocking operations - excess console output will cause a decreased rate of collection. Hence the reasoning for the defaults currently set

**Comment by matthewhillier** [comment]
Did the logging options added in the 2.0 update solve this one for you guys?

**Comment by Pricetx** [comment]
Sorry for taking a year to get back to you, but yes this did solve the issue!
