### ISSUE TITLE
Provided Table Structure is Incorrect

### ISSUE THREAD

**Issue by zeronoun** [XIVStats/XIVStats-Gatherer-Java#27]
The structure for `tblplayers` listed on the main project page is out of date with the most recent SQLdump (2018-01).

It is now as follows:

```
columns = [
           'id',
           'name',
           'realm',
           'race',
           'gender',
           'grand_company',
           'free_company',
           'level_gladiator',
           'level_pugilist',
           'level_marauder',
           'level_lancer',
           'level_archer',
           'level_rogue',
           'level_conjurer',
           'level_thaumaturge',
           'level_arcanist',
           'level_darkknight',
           'level_machinist',
           'level_astrologian',
           'level_scholar',
           'level_redmage',
           'level_samurai',
           'level_carpenter',
           'level_blacksmith',
           'level_armorer',
           'level_goldsmith',
           'level_leatherworker',
           'level_weaver',
           'level_alchemist',
           'level_culinarian',
           'level_miner',
           'level_botanist',
           'level_fisher',
           'p30days',
           'p60days',
           'p90days',
           'p180days',
           'p270days',
           'p360days',
           'p450days',
           'p630days',
           'p960days',
           'prearr',
           'prehw',
           'presb',
           'arrartbook',
           'hwartbookone',
           'hwartbooktwo',
           'hasencyclopedia',
           'beforemeteor',
           'beforethefall',
           'ps4collectors',
           'soundtrack',
           'saweternalbond',
           'sightseeing',
           'comm50',
           'moogleplush',
           'topazcarbuncleplush',
           'emeraldcarbuncleplush',
           'hildibrand',
           'dideternalbond',
           'arrcollector',
           'kobold',
           'sahagin',
           'amaljaa',
           'sylph',
           'moogle',
           'vanuvanu',
           'vath',
           'arr_25_complete',
           'hw_complete',
           'hw_31_complete',
           'hw_33_complete',
           'legacy_player',
           'mounts',
           'minions'
          ]
```

All of these dumps seem to be missing the two most interesting features: `date_active` and `is_active`.

I'm doing a pet project using topic modeling of Lodestone forum post titles against various data points, namely active subscribers. I could key these counts manually from the ffxivcensus site, but where's the fun in that? 😄👍🏼

**Comment by Pricetx** [comment]
Hi, thanks for your interest in our little project.

Thanks for pointing out the DB schema being out of date in the description, i'll get that updated.

Unfortunately we trialed a system of checking the date on the profile images for players to determine when accounts were last used, but due to inconsistent behaviour throughout the Lodestone this didn't give us accurate results. For the purposes of the website, active players are currently just determined by whether a player has collected the Yol mount during the 4.0 story. Accurate activity checking is something we'd love to have but unfortunately nobody has the time to invest in developing it.

To best answer your question for the moment, if you want to automatically grab the figures that match the site, look for the Yol mount under "mounts".

Let me know if you have any further questions.

**Comment by zeronoun** [comment]
Thanks for the info!

**Comment by matthewhillier** [comment]
Just a small bit of intel on the topic of "Active" characters. I noticed the following [maintenance notice](https://na.finalfantasyxiv.com/lodestone/news/detail/b3a4888393486f71498ee1c39802ca6dc4888069) on the lodestone following the 4.2 launch:

> If your character image is still not being reflected correctly, logging in to FINAL FANTASY XIV with the character in question and changing your equipment will cause the character image to refresh properly.

This may mean that the image is a valid way of determining activity, but doesn't make sense on it's own. It's been in my head for a while to keep a record of character history, which in-conjunction with the image update, could start to build a more robust picture of "activity" based on levelling (actively levelling), gearing (actively gearing) and image (actively playing more than one class/job) changes from one month to the next. Combine with Minions, Mounts and any other details a player makes public, could start to build a good picture here?
