### ISSUE TITLE
Statistics about the software

### ISSUE THREAD

**Issue by kennedyoliveira** [XIVStats/XIVStats-Gatherer-Java#33]
Hey guys,

do you have some more recent statistics on how long does it take to run for the entire base?
How many characters are you gathering per seconds/minutes?
What are the hardware you are using to run it?
Bandwidth consumption?
CPU, MEM usage?

I'm curious on the performance of the current implementation, also, would be very good to provide this information in the README, so other people can have a notion of what they can expect for the current version, especially a more recent "high id", so it won't run forever, and also give some information so others can help you improve it :)

Anyway, good work doing it, it's very interesting.

**Comment by matthewhillier** [comment]
@Pricetx can probably help you with the runtime stats, but we're very much dependent on the lodestone and surrounding network infrastructure.

The "top" ID number is a moving goal-post unfortunately. Even while working on #30, it's become obvious that new characters are being created almost constantly and so the number is always "out of date" the moment we know about it. That's not necessarily a bad thing, but it is pretty interesting (especially when you start asking "why" questions about where all those characters go...) 😄 

Maybe some people would find it interesting to have the runtime stats included in the site somewhere, just as piece of trivia?

**Comment by Pricetx** [comment]
Hello,

Sorry for the very slow response, I've not been too involved in the project over the past year.

How long does it take to run the entire base?
The last run took 14 days with 64 threads configured

How many characters are you gathering per seconds/minutes?
Scanning a total of around 25 million IDs in 14 days = about 75,000 characters per hour

What are the hardware you are using to run it?
At the moment, it is running in a fairly modest VM. It has 2GB of RAM, 2 CPU cores and a 100mbit network connection.

Bandwidth consumption?
Even at 64 threads, fairly minimal. Typically 3.5-4 mbit/sec download and 300 kbit/sec upload

CPU, MEM usage?
The two CPU cores tend to sit at 30-60%
The census doesn't appear to run observably quicker beyond about 1G of heap size allocated. It runs without great issue on the VM with 2GB of RAM.

Before I close this I will make sure to put some of this info in the README as you suggested, thanks!
