### ISSUE TITLE
Some fields not populating

### ISSUE THREAD

**Issue by Pricetx** [XIVStats/XIVStats-Gatherer-Java#37]
I was beginning to debug the active player count on ffxivcensus.com by running the latest version of the java gatherer in a test environment.

When running the gatherer on my character (8308898) there appears to be a number of empty fields. I have attached a CSV showing an excerpt (please ignore the formatting with the mounts, limitation of csv).

The following fields all appear to be blank:
- p30days
- p60days
- p90days
- p180days
- p270days
- p360days
- p450days
- p630days
- p960days
- prearr
- prehw
- presb
- arrartbook
- hwartbookone
- hwartbooktwo
- hasencyclopedia
- beforemeteor
- beforethefall
- ps4collectors
- soundtrack
-saweternalbond
- sightseeing
- comm50
- moogleplush
- topazcarbuncleplush
- emeraldcarbuncleplush
- hildibrand
- dideternalbond
- arrcollector
- kobold
- sahagin
- amaljaa
- sylph
- moogle
- vanuvanu
- vath
- arr_25_complete
- hw_complete
- hw_31_complete
- hw_33_complete
- sb_complete
- legacy_player

Some of these fields may intentionally be blank as my character doesn't meet all of the requirements, however, a number of them should be populated.

The arguments used when calling the gatherer:
/usr/bin/java -Xmx1024M -jar XIVStats-Gatherer-Java-v2.0.0.jar -s 8308898 -f 8308898

The version of the gatherer is the most recent build on ci.reidweb.com. This is build 78 and is built from commit 4f9f2c8, which at the time of writing is the latest commit to master.

I have tried re-creating the MySQL database in case that was somehow an issue, but this did not affect the result.

It does not look like this is the issue currently facing the live environment as it has data for the soundtracks, collectors editions etc, so I will continue investigating that.

[8308898.xlsx](https://github.com/XIVStats/XIVStats-Gatherer-Java/files/2612237/8308898.xlsx)

**Comment by Pricetx** [comment]
Based on the documentation, it would appear that the affected fields are all of the fields that are populated based on minion / mount ownership. The "mounts" and "minions" columns are both populated during my test run so the gatherer is not having difficulty gathering this information, but there may be an issue with the process that checks for their presence and updates the relevant fields.

**Comment by Pricetx** [comment]
These fields are all populated by GetPlayer in PlayerBuilder.java. They use the methods doesPlayerHaveMinion and doesPlayerHaveMount. There is no segregation between these fields and others, so it does not appear there's a missing or undocumented flag to populate these.

Either doesPlayerHaveMinion/Mount is returning false all of the time or there is some issue with writing the value to the database.

**Comment by Pricetx** [comment]
I have tried running all of the successful builds of the v2 Gatherer (going back to 30-Nov-2017). All of the builds produce the same result, with none of them populating these fields. I could look at v1.x builds in order to fix the live site in the meantime, but if I do I will also have to look at what the most recent version of the PHP is that supports the DB structure.

**Comment by matthewhillier** [comment]
I _think_ we may be bumping into this one: https://stackoverflow.com/a/11609597.

Seems there's an issue in MySQL (Maria seems to have inherited it), where values stored in a `bit` column aren't always returned correctly (see here for more detail: https://www.xaprb.com/blog/2006/04/11/bit-values-in-mysql/).

As an example, running `select legacy_player from tblplayers limit 10;` on the live db gives us:

```
+---------------+
| legacy_player |
+---------------+
|               |
|              |
|              |
|               |
|               |
|               |
|               |
|               |
|               |
|              |
+---------------+
10 rows in set (0.00 sec)
```

Whereas if we use the "hack" from StackOverflow `select legacy_player+0 from tblplayers limit 10;` we get the result:

```
+-----------------+
| legacy_player+0 |
+-----------------+
|               0 |
|               1 |
|               1 |
|               0 |
|               0 |
|               0 |
|               0 |
|               0 |
|               0 |
|               1 |
+-----------------+
10 rows in set (0.10 sec)
```

It seems like _some_ GUI tools such as MySQL Workbench are able to translate and handle this properly, but others aren't - I'm assuming the CLI Client is among them, at this point.

Seeing as we're getting the inactive stats in the produced HTML at the moment, I _think_ this might be a red-herring and the PHP client is working just fine in this case. The Active stats are going to be related to the mounts & minions columns being completely missing.

**Comment by matthewhillier** [comment]
Ran the PHP code against the `dev` database and we are indeed getting numbers for statistics which rely on those `bit` fields, so they are being picked up by the PHP correctly and this is an issue with the MySQL CLI Client interpreting raw `bit` field columns.

**Comment by Pricetx** [comment]
Hello,

Ironically, I didn't get as far as testing the PHP due to spotting what looked like an issue populating the fields in the DB.

I have kicked off a 1 million ID scan in the dev environment with the newest Java and PHP. If this works fine I will put it in place ahead of the December scan.

Thanks for the help.
