### ISSUE TITLE
Add Eureka Elemental Level Stats

### ISSUE THREAD

**Issue by Crakila** [XIVStats/XIVStats-Gatherer-Java#43]
So looking at LuckyBancho's stats that they recently released here: https://www.reddit.com/r/ffxiv/comments/apfx16/luckybancho_unofficial_census_10_february_2019/

It seems that they are tracking for Elemental Levels (it's under the Class/Job tab on a character's page)
As of Patch 4.55 (Released today 12th Feb 2019), there are 4 "Eureka" instances, with there being Level caps for each zone. Now it is possible to level past 20 in Anemos but I figured that the figures could be displayed in the next (March report) once players have got to max level in Hydatos.

* Eureka Anemos - 1 - 20
* Eureka Pagos - 21 - 35
* Eureka Pyros - 36 - 50
* Eureka Hydatos - 51 - 60

My idea would be that the result would be:
* "Total Players who have played Eureka":  (eg. Everyone that has a Elemental Level)
* "Players who are levelling in Eureka: Hydatos" (eg. Anyone that is between 50 and 59)

**Comment by matthewhillier** [comment]
Thanks, @fahy! I've submitted a pull request which pulls in the data from the lodestone so that we can use it in the PHP in some way.

Once the census is stable again, we can jump back into the PHP and update the census page.

**Comment by matthewhillier** [comment]
The backend for this is done and we're collecting Eureka level. Front-End now needs some work :)
