### ISSUE TITLE
Data centre now being included in realm name

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats-Gatherer-Java#49]
Taking a look at the [test results](https://dev.azure.com/xivstats/XIVStats-Gatherer-Java/_build/results?buildId=45&view=ms.vss-test-web.build-test-results-tab&runId=16&resultId=100009&paneView=debug) and an [example character](
https://eu.finalfantasyxiv.com/lodestone/character/11886902/) it looks like the data centre is now being included in parentheses after the realm name. This is going to cause issues with the realm count as @Pricetx has noted to me offline.

**Comment by matthewhillier** [comment]
Submitted Pull Request #50 to fix the issue with the Server Names
