### ISSUE TITLE
Verbosity switch

### ISSUE THREAD

**Issue by ghost** [XIVStats/XIVStats-Gatherer-Java#5]
A way to make it only notify if a character _cannot_ be added to the database would be useful for me (but, it's just a request, no worries :D)

**Comment by ReidWeb** [comment]
So are you looking for it to print something like

```
Character {x} does not exist.
```

When a character/user id does not exist on the lodestone.

Or are you looking for it to tell you when a database write of a record fails?

**Comment by ghost** [comment]
Just when a failure occurs

**Comment by ReidWeb** [comment]
When a record write failure occurs the system will wait 1 second and attempt to write the record again and print a message. If the system fails to write the second time a stack trace will be written to the console.

[See this code](https://github.com/XIVStats/XIVStats-Gatherer-Java/blob/master/src/main/java/com/ffxivcensus/gatherer/Gatherer.java#L39).

A verbosity switch already exists within the program, run with `-q` flag to print nothing except initiation and final completion message. Run with `-D` to print everything, including character id's that do not exist.

**Comment by ghost** [comment]
Right, but all I want to see is when a failure occurs, if that's possible.

**Comment by ReidWeb** [comment]
@hmschreck I can add that as a feature, adding to requested feature list

**Comment by ReidWeb** [comment]
I have added the '-F' flag to the program, run the program with flags '-qF' to print only records that aren't gathered because they don't exist.

**Comment by ReidWeb** [comment]
Hopefully this rectifies your request.

**Comment by ghost** [comment]
I was actually more worried about things not going in the database, but
this will be useful as well!

**Comment by ReidWeb** [comment]
Ah right, if that occurs an error will be printed: `Error: Record write failure, reattempting write`.
It will then reattempt the write, and if it fails it'll print you the appropriate errors to the console to allow you to debug.
