### ISSUE TITLE
Did SE really not block you with 64 threads?

### ISSUE THREAD

**Issue by Helios747** [XIVStats/XIVStats-Gatherer-Java#60]
I decided to run this collector myself because it looks like ffxivcensus.com data is pretty old, have it running on an EC2 instance in japan and it's chugging along fine but I'm really just curious, did SE really not block your IP??

This doesn't seem to care about any sort of rate limiting

**Comment by ReidWeb** [comment]
Out of interest did you get what anywhere with this, the last time we updated the site corresponds with when Square changed the DOM of the significantly. So what's here won't run.

@Pricetx would be the one who could comment on our thread limits in detail

**Comment by matthewhillier** [comment]
Just taking a look at the gatherer with the 6.0 updates now (Committing under #61).

Threads self-manage, so they'll keep going until the SQEX server tells us to back-off, in which they go into "cooldown". It was a lot more than 64 threads in the past, so this is already scaled-back a lot from where it started off :)
