### ISSUE TITLE
Endwalker 6.0 Updates

### ISSUE THREAD

**Issue by matthewhillier** [XIVStats/XIVStats-Gatherer-Java#61]

**Comment by ReidWeb** [comment]
Hey Matt,
The DOM for mounts and minions has changed so significantly it required a rewrite of half the codebase unfortunately. So haven't gotten to it.

I'm short the only way to ascertain what mounts a player has now is by the image URL. To get item id or name you need to interact with the dom. Something we can't do without the use of selenium web driver or something to that effect.

I'm currently planning out the steps required to get everything working afresh, but also make the maintenance doable by anyone. But that's a fair way off completion.

I've described my thought process for addressing this problem in xivstats/lodestone#24

**Comment by matthewhillier** [comment]
Hi @ReidWeb - thanks for this!

I think I already solved the Mounts & Minions parsing in #55 (See commit: https://github.com/XIVStats/XIVStats-Gatherer-Java/commit/5eace13442d4d1e5e3fa2d00327a7d0714c6d88f). At least at the moment, the current parser seems to be working.

I think it's done essentially what you're describing in [XIVStats/lodestone#24](https://github.com/XIVStats/lodestone/issues/24), just in a bit more of a pared-down way - but feel free to check out and see whether there's anything missing.

Cheers!

**Comment by ReidWeb** [comment]
Oh okay you literally did this two years ago. Shows how much I remember

Should be grand then.

**Comment by matthewhillier** [comment]
Only because I remember it being a pain in the whatsits 🙄
