### ISSUE TITLE
Characters on a PvP Team set free_company and grand_company field to 'none'

### ISSUE THREAD

**Issue by akamichoff192** [XIVStats/XIVStats-Gatherer-Java#64]
As the main story has you choose a Grand Company, I found it odd that there were active characters (with the Endwalker MSQ minion) with no Grand Company. Digging a bit deeper, I found that characters in the database with that minion and their grand_company field set to 'none' had one thing in common; having a PvP team listed on their Lodestone page. Admittedly, I only checked a couple IDs, but after a dozen or so I assumed the problem extends to all 17,145.

I think the issue stems from characters on PvP teams having an additional character-block field on their Lodestone page, causing both the Free Company and Grand Company functions in the PlayerBuilder class to fall through when the number of elements is 6, rather than 3-5. I also assume the case of having 5 elements could refer to a character with a PvP team but no Free Company and cause an issue somewhere. I don't think a character can have a PvP team with no Grand Company, but I'm not 100% certain on that, as I don't know exactly when PvP is unlocked.

If you'd like the full list of IDs, the query I ran was:
SELECT id FROM tblplayers WHERE grand_company = 'none' AND minions like '%Wind-up Herois%';

For simplicity, here's the first 5 results so you can check their pages:
5313
6855
6913
8283
9307

**Comment by ReidWeb** [comment]
Ah, yeah that would make sense thanks for raising this.

Won't lie I didn't even know PvP team was a thing 😂
