### ISSUE TITLE
Feature: Oceania DC

### ISSUE THREAD

**Issue by Nimbus88** [XIVStats/XIVStats-Gatherer-Java#66]
Out of curiosity, when the Oceania Servers and DC get released, would this automatically be accounted for or would be a feature item?

**Comment by Crakila** [comment]
Heya.

It'll automatically account for it on the Java side. 

For the website side of things, it has already been updated:
https://github.com/XIVStats/XIVStats/commit/174adba8846c655780ab4b72d97582b4b06a536c

We don't expect to have a proper number for a couple of months until sever transfers to Oceania calm down a bit!

**Comment by Nimbus88** [comment]
Thanks!
