### ISSUE TITLE
I am not able to see the graphs.

### ISSUE THREAD

**Issue by STARSAGECRAZE** [XIVStats/XIVStats-Gatherer-Java#72]
![bandicam 2024-09-03 07-53-25-826](https://github.com/user-attachments/assets/e3fcdf08-b568-4f35-bf53-08f44caafd8d)

**Comment by ReidWeb** [comment]
Please check the terminal of your browser. Are you any errors

**Comment by STARSAGECRAZE** [comment]
Oh thank you for the suggestion. 
I disabled my "malwarebytes browser plugin" which fixed the issue. 
Must have been a recent update that started flagging the site.

**Comment by STARSAGECRAZE** [comment]
![bandicam 2024-09-03 08-04-41-651](https://github.com/user-attachments/assets/8aa88dce-e062-4af1-8e76-6032eec89f3d)
Fixed
